Mohamadreza/eng 601 front end delete button in contacts page
Lo-Agency-Internship/Kerio pull request #162
Opened 2022-11-06 15:04 UTC by mhmdrezanaderi

# Description

handle batch delete 

Fixes # 601(Delete button in contacts page)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

delete some contacts and see results

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-11-07 09:14 UTC, ferizana92 approved these changes

2022-11-09 07:47 UTC, samikia reviewed
please check `deleteContacts` in `api.tsx` and `index.tsx`

2022-11-09 16:55 UTC, samikia requested changes
please check the `api.tsx` line 235 `deleteContacts` and check `index,.tsx` line 10 `deleteContacts`

2022-11-13 18:03 UTC, samikia approved these changes
thanks everything works great!!

2022-11-13 18:03 UTC, merged